server:
  port: 8001
spring:
  application:
    name: user-service
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/cloud
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
